#ifndef __LIMITS_H__
#define __LIMITS_H__

#define BUFFER_SIZE_LIMIT 255
#define BACKLOG_LIMIT 1024
#define SERVER_PORT_NUM 5825
#define PORT_NUM_SIZE 5
#define SERVER_IP "127.0.0.1"
#define USERNAME_SIZE_LIMIT 10
#define PASSWORD_SIZE_LIMIT 10
#define REPLY_SIZE_LIMIT 15
#define GROUP_NAME_SIZE_LIMIT 10
#define NUM_OF_USERS_LIMIT 100
#define NUM_OF_GROUPS_LIMIT 100
#define NUM_OF_IP_ADDR 100
#define IP_ADDR_SIZE_LIMIT 12
#define MESSAGE_SIZE_LIMIT 220
#define SUCCESS 0
#define FAIL -1
#define DUPLICATE 1
#define NOT_FOUND 1
#define TRUE 1
#define FALSE 0

#endif /* __LIMITS_H__ */